Update terragrunt_destroy.yml

diff --git a/.github/workflows/terragrunt_destroy.yml b/.github/workflows/terragrunt_destroy.yml
--- a/.github/workflows/terragrunt_destroy.yml
+++ b/.github/workflows/terragrunt_destroy.yml
@@ -37,21 +37,21 @@ jobs:
           sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
           sudo chmod +x /usr/local/bin/terragrunt
 
-      - name: Terragrunt Destroy gke-cluster
-        run: terragrunt destroy --auto-approve --non-interactive --working-dir=live/dev/gke-cluster
+  #    - name: Terragrunt Destroy gke-cluster
+   #     run: terragrunt destroy --auto-approve --non-interactive --working-dir=live/dev/gke-cluster
 
-      - name: Wait for GKE cluster deletion
-        run: |
-          RETRIES=20
-          while gcloud container clusters describe gke-cluster --region=$GOOGLE_REGION --project=$GOOGLE_PROJECT &> /dev/null; do
-            echo "Waiting for GKE cluster to be deleted..."
-            sleep 15
-            RETRIES=$((RETRIES-1))
-            if [ $RETRIES -eq 0 ]; then
-              echo "GKE cluster deletion timeout"
-              exit 1
-            fi
-          done
+  #    - name: Wait for GKE cluster deletion
+    #    run: |
+     #     RETRIES=20
+      #    while gcloud container clusters describe gke-cluster --region=$GOOGLE_REGION --project=$GOOGLE_PROJECT &> /dev/null; do
+        #    echo "Waiting for GKE cluster to be deleted..."
+         #   sleep 15
+          #  RETRIES=$((RETRIES-1))
+        #    if [ $RETRIES -eq 0 ]; then
+          #    echo "GKE cluster deletion timeout"
+          #    exit 1
+         #   fi
+        #  done
 
       - name: Terragrunt Destroy firewall
         run: terragrunt destroy --auto-approve --non-interactive --working-dir=live/dev/firewall
